# Blueprint metadata
blueprint:
  name: "Time / Weekday Action"
  description: "A very small and simple automation for executing an action (or several) at a specific time on a selectable day of the week."
  domain: automation
  author: "Sven Koepfer"
  input:
    time:
      name: Time
      description: Time at which the action should be carried out.
      default: "10:00:00"
      selector:
        time: {}
    weekday:
      name: Weekday
      description: Day of the week on which the action should be carried out.
      default: [mon, tue, wed, thu, fri]
      selector:
        select:
          options:
          - label: Monday
            value: mon
          - label: Tuesday
            value: tue
          - label: Wednesday
            value: wed
          - label: Thursday
            value: thu
          - label: Friday
            value: fri
          - label: Saturday
            value: sat
          - label: Sunday
            value: sun
          custom_value: false
          multiple: true
    actions:
      name: Actions
      selector:
        action:

trigger:
  - platform: time
    at: !input time

condition:
  - condition: time
    weekday: !input weekday

action:
  - choose: []
    default: !input actions

mode: single
max_exceeded: silent